"""add cascade

Revision ID: 1b7ce5112992
Revises: 24bd50e6afee
Create Date: 2026-07-17 20:58:56.528483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7ce5112992'
down_revision: Union[str, None] = '24bd50e6afee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clone_images_script_id_fkey', 'clone_images', type_='foreignkey')
    op.create_foreign_key(None, 'clone_images', 'clone_scripts', ['script_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('clone_script_segments_script_id_fkey', 'clone_script_segments', type_='foreignkey')
    op.create_foreign_key(None, 'clone_script_segments', 'clone_scripts', ['script_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('clone_scripts_script_id_fkey', 'clone_scripts', type_='foreignkey')
    op.create_foreign_key(None, 'clone_scripts', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('clone_videos_video_id_fkey', 'clone_videos', type_='foreignkey')
    op.create_foreign_key(None, 'clone_videos', 'clone_scripts', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('clone_voices_script_id_fkey', 'clone_voices', type_='foreignkey')
    op.create_foreign_key(None, 'clone_voices', 'clone_scripts', ['script_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('script_segments_script_id_fkey', 'script_segments', type_='foreignkey')
    op.create_foreign_key(None, 'script_segments', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('scripts_video_id_fkey', 'scripts', type_='foreignkey')
    op.create_foreign_key(None, 'scripts', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scripts', type_='foreignkey')
    op.create_foreign_key('scripts_video_id_fkey', 'scripts', 'videos', ['video_id'], ['id'])
    op.drop_constraint(None, 'script_segments', type_='foreignkey')
    op.create_foreign_key('script_segments_script_id_fkey', 'script_segments', 'scripts', ['script_id'], ['id'])
    op.drop_constraint(None, 'clone_voices', type_='foreignkey')
    op.create_foreign_key('clone_voices_script_id_fkey', 'clone_voices', 'clone_scripts', ['script_id'], ['id'])
    op.drop_constraint(None, 'clone_videos', type_='foreignkey')
    op.create_foreign_key('clone_videos_video_id_fkey', 'clone_videos', 'clone_scripts', ['video_id'], ['id'])
    op.drop_constraint(None, 'clone_scripts', type_='foreignkey')
    op.create_foreign_key('clone_scripts_script_id_fkey', 'clone_scripts', 'scripts', ['script_id'], ['id'])
    op.drop_constraint(None, 'clone_script_segments', type_='foreignkey')
    op.create_foreign_key('clone_script_segments_script_id_fkey', 'clone_script_segments', 'clone_scripts', ['script_id'], ['id'])
    op.drop_constraint(None, 'clone_images', type_='foreignkey')
    op.create_foreign_key('clone_images_script_id_fkey', 'clone_images', 'clone_scripts', ['script_id'], ['id'])
    # ### end Alembic commands ###
