"""add image prompt

Revision ID: 24bd50e6afee
Revises: 99c90f70710a
Create Date: 2026-07-10 16:50:05.236006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bd50e6afee'
down_revision: Union[str, None] = '99c90f70710a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_images', sa.Column('prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clone_images', 'prompt')
    # ### end Alembic commands ###
