"""add zeed in CloneImage

Revision ID: 497ec58be36f
Revises: 546c6d44092d
Create Date: 2026-07-25 19:35:36.464147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497ec58be36f'
down_revision: Union[str, None] = '546c6d44092d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_role_images', sa.Column('seed', sa.BigInteger(), nullable=True, comment='生图 Seed'))
    op.add_column('clone_scene_images', sa.Column('seed', sa.BigInteger(), nullable=True, comment='生图 Seed'))
    op.add_column('clone_segment_images', sa.Column('seed', sa.BigInteger(), nullable=True, comment='生图 Seed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clone_segment_images', 'seed')
    op.drop_column('clone_scene_images', 'seed')
    op.drop_column('clone_role_images', 'seed')
    # ### end Alembic commands ###
