"""add status in CloneImage

Revision ID: 546c6d44092d
Revises: b6491053b60f
Create Date: 2026-07-25 18:39:54.152513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '546c6d44092d'
down_revision: Union[str, None] = 'b6491053b60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

videosource_enum = postgresql.ENUM(
    'local', 'douyin',
    name='videosource'
)

videostatus_enum = postgresql.ENUM(
    'pending', 'processing', 'done', 'failed',
    name='videostatus'
)

segmenttype_enum = postgresql.ENUM(
    'shot', 'dialogue', 'mixed',
    name='segmenttype'
)

segmentimagetype_enum = postgresql.ENUM(
    'FIRST_FRAME', 'LAST_FRAME',
    name='segmentimagetype'
)

generatestatus_enum = postgresql.ENUM(
    'PENDING', 'PROCESSING', 'SUCCESS', 'FAILED',
    name='generatestatus'
)

clonestatus_enum = postgresql.ENUM(
    'PENDING', 'PLOT', 'PLOT_DONE', 'VOICE', 'VOICE_DONE', 
    'SEGMENTS', 'SEGMENTS_DONE', 'IMAGE', 'IMAGE_DONE', 
    'VIDEO', 'DONE', 'FAILED',
    name='clonestatus'
)

# 把它们放进一个列表，方便批量操作
all_enums = [
    videosource_enum,
    videostatus_enum,
    segmenttype_enum,
    segmentimagetype_enum,
    generatestatus_enum,
    clonestatus_enum
]

def upgrade() -> None:
    
    for pg_enum in all_enums:
        pg_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_role_images', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='generatestatus'), nullable=True, comment='重新生成图片人物状态'))
    op.alter_column('clone_role_images', 'desc',
               existing_type=sa.VARCHAR(length=128),
               comment='前端展示描述信息，例如肖像、场景、首帧、尾帧',
               existing_comment='补充描述信息，例如肖像、场景、首帧、尾帧',
               existing_nullable=True)
    op.add_column('clone_scene_images', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='generatestatus'), nullable=True, comment='重新生成图片人物状态'))
    op.alter_column('clone_scene_images', 'desc',
               existing_type=sa.VARCHAR(length=128),
               comment='前端展示描述信息，例如肖像、场景、首帧、尾帧',
               existing_comment='补充描述信息，例如肖像、场景、首帧、尾帧',
               existing_nullable=True)
    op.add_column('clone_segment_images', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='generatestatus'), nullable=True, comment='重新生成图片人物状态'))
    op.alter_column('clone_segment_images', 'desc',
               existing_type=sa.VARCHAR(length=128),
               comment='前端展示描述信息，例如肖像、场景、首帧、尾帧',
               existing_comment='补充描述信息，例如肖像、场景、首帧、尾帧',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clone_segment_images', 'desc',
               existing_type=sa.VARCHAR(length=128),
               comment='补充描述信息，例如肖像、场景、首帧、尾帧',
               existing_comment='前端展示描述信息，例如肖像、场景、首帧、尾帧',
               existing_nullable=True)
    op.drop_column('clone_segment_images', 'status')
    op.alter_column('clone_scene_images', 'desc',
               existing_type=sa.VARCHAR(length=128),
               comment='补充描述信息，例如肖像、场景、首帧、尾帧',
               existing_comment='前端展示描述信息，例如肖像、场景、首帧、尾帧',
               existing_nullable=True)
    op.drop_column('clone_scene_images', 'status')
    op.alter_column('clone_role_images', 'desc',
               existing_type=sa.VARCHAR(length=128),
               comment='补充描述信息，例如肖像、场景、首帧、尾帧',
               existing_comment='前端展示描述信息，例如肖像、场景、首帧、尾帧',
               existing_nullable=True)
    op.drop_column('clone_role_images', 'status')
    # ### end Alembic commands ###
