"""add faceless to clone_role_images

Revision ID: 6be585a63cee
Revises: c443ac8b8734
Create Date: 2026-08-01 22:24:33.282622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be585a63cee'
down_revision: Union[str, None] = 'c443ac8b8734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_role_images', sa.Column('faceless', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clone_role_images', 'faceless')
    # ### end Alembic commands ###
