"""add_clone_theme

Revision ID: 8631600b9bce
Revises: acbc3d8f3625
Create Date: 2026-06-02 18:05:24.115338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8631600b9bce'
down_revision: Union[str, None] = 'acbc3d8f3625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_script_segments', sa.Column('segment_type', sa.Enum('SHOT', 'DIALOGUE', 'MIXED', name='segmenttype'), nullable=True))
    op.add_column('clone_scripts', sa.Column('clone_theme', sa.String(length=255), nullable=True, comment='复刻视频标题'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clone_scripts', 'clone_theme')
    op.drop_column('clone_script_segments', 'segment_type')
    # ### end Alembic commands ###
