"""add table clone_segment_video

Revision ID: 90ca846aba78
Revises: ebbd4c00f32c
Create Date: 2026-08-01 01:13:52.044484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90ca846aba78'
down_revision: Union[str, None] = 'ebbd4c00f32c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clone_segment_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clone_script_sgement_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column(
        'status', 
        postgresql.ENUM('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='generatestatus', create_type=False), 
        nullable=False, 
        comment='重新生成视频状态'
    ),
    # sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='generatestatus', create_type=False), nullable=False, comment='重新生成视频状态'),
    sa.Column('seed', sa.BigInteger(), nullable=True, comment='生图 Seed'),
    sa.Column('desc', sa.String(length=128), nullable=True, comment='前端展示描述信息'),
    sa.Column('version', sa.Integer(), nullable=False, comment='图片版本'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clone_script_sgement_id'], ['clone_script_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clone_segment_video_id'), 'clone_segment_video', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clone_segment_video_id'), table_name='clone_segment_video')
    op.drop_table('clone_segment_video')
    # ### end Alembic commands ###
