"""add_clone_fields

Revision ID: acbc3d8f3625
Revises: 33bde59d3e98
Create Date: 2026-06-02 15:08:12.688879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acbc3d8f3625'
down_revision: Union[str, None] = '33bde59d3e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clone_script_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('shot_description', sa.Text(), nullable=True),
    sa.Column('dialogue', sa.JSON(), nullable=True),
    # sa.Column('segment_type', sa.Enum('SHOT', 'DIALOGUE', 'MIXED', name='segmenttype'), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['clone_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clone_script_segments_id'), 'clone_script_segments', ['id'], unique=False)
    op.create_table('clone_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['clone_scripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_index(op.f('ix_clone_videos_id'), 'clone_videos', ['id'], unique=False)
    op.add_column('clone_scripts', sa.Column('clone_parse_pointer', sa.Text(), nullable=True, comment='复刻解析重点信息'))
    op.add_column('clone_scripts', sa.Column('clone_parse_script', sa.JSON(), nullable=True, comment='复刻解析剧本脚本'))
    op.add_column('clone_scripts', sa.Column('clone_parse_file_path', sa.Text(), nullable=True, comment='复刻解析结果文件路径,markdown格式'))
    op.add_column('clone_scripts', sa.Column('clone_content', sa.JSON(), nullable=True, comment='复刻完整剧本内容，包含分镜、台词等信息'))
    op.drop_column('clone_scripts', 'clone_script_content')
    op.drop_column('clone_scripts', 'clone_script_path')
    op.alter_column('scripts', 'parse_pointer',
               existing_type=sa.TEXT(),
               comment='解析重点信息',
               existing_nullable=True)
    op.alter_column('scripts', 'parse_script',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='解析剧本脚本',
               existing_nullable=True)
    op.alter_column('scripts', 'parse_file_path',
               existing_type=sa.TEXT(),
               comment='解析结果文件路径,markdown格式',
               existing_nullable=True)
    op.alter_column('scripts', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='完整剧本内容，包含分镜、台词等信息',
               existing_nullable=True)
    op.alter_column('videos', 'clone_status',
               existing_type=postgresql.ENUM('PENDING', 'CLONING', 'CLONE_DONE', 'CLONE_FAILED', name='clonestatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::clonestatus"))
    op.alter_column('videos', 'clone_progress',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'clone_progress',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('videos', 'clone_status',
               existing_type=postgresql.ENUM('PENDING', 'CLONING', 'CLONE_DONE', 'CLONE_FAILED', name='clonestatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::clonestatus"))
    op.alter_column('scripts', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='完整剧本内容，包含分镜、台词等信息',
               existing_nullable=True)
    op.alter_column('scripts', 'parse_file_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='解析结果文件路径,markdown格式',
               existing_nullable=True)
    op.alter_column('scripts', 'parse_script',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='解析剧本脚本',
               existing_nullable=True)
    op.alter_column('scripts', 'parse_pointer',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='解析重点信息',
               existing_nullable=True)
    op.add_column('clone_scripts', sa.Column('clone_script_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clone_scripts', sa.Column('clone_script_content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('clone_scripts', 'clone_content')
    op.drop_column('clone_scripts', 'clone_parse_file_path')
    op.drop_column('clone_scripts', 'clone_parse_script')
    op.drop_column('clone_scripts', 'clone_parse_pointer')
    op.drop_index(op.f('ix_clone_videos_id'), table_name='clone_videos')
    op.drop_table('clone_videos')
    op.drop_index(op.f('ix_clone_script_segments_id'), table_name='clone_script_segments')
    op.drop_table('clone_script_segments')
    # ### end Alembic commands ###
