"""image details

Revision ID: b6491053b60f
Revises: cb69ce16e987
Create Date: 2026-07-23 20:31:31.116135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6491053b60f'
down_revision: Union[str, None] = 'cb69ce16e987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clone_role_images',
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('role_name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True, comment='补充描述信息，例如肖像、场景、首帧、尾帧'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['clone_scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clone_role_images_id'), 'clone_role_images', ['id'], unique=False)
    op.create_index(op.f('ix_clone_role_images_role_name'), 'clone_role_images', ['role_name'], unique=False)
    op.create_table('clone_scene_images',
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('scene_name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True, comment='补充描述信息，例如肖像、场景、首帧、尾帧'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['clone_scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clone_scene_images_id'), 'clone_scene_images', ['id'], unique=False)
    op.create_index(op.f('ix_clone_scene_images_scene_name'), 'clone_scene_images', ['scene_name'], unique=False)
    op.create_table('clone_segment_images',
    sa.Column('clone_script_sgement_id', sa.Integer(), nullable=True),
    sa.Column('clone_segment_image_type', sa.Enum('FIRST_FRAME', 'LAST_FRAME', name='segmentimagetype'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True, comment='补充描述信息，例如肖像、场景、首帧、尾帧'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clone_script_sgement_id'], ['clone_script_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clone_segment_images_id'), 'clone_segment_images', ['id'], unique=False)
    op.drop_column('clone_script_segments', 'first_frame_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_script_segments', sa.Column('first_frame_path', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='分镜首帧路径'))
    op.drop_index(op.f('ix_clone_segment_images_id'), table_name='clone_segment_images')
    op.drop_table('clone_segment_images')
    op.drop_index(op.f('ix_clone_scene_images_scene_name'), table_name='clone_scene_images')
    op.drop_index(op.f('ix_clone_scene_images_id'), table_name='clone_scene_images')
    op.drop_table('clone_scene_images')
    op.drop_index(op.f('ix_clone_role_images_role_name'), table_name='clone_role_images')
    op.drop_index(op.f('ix_clone_role_images_id'), table_name='clone_role_images')
    op.drop_table('clone_role_images')
    # ### end Alembic commands ###
