"""add version to imagebase

Revision ID: be40a92bfaaf
Revises: 497ec58be36f
Create Date: 2026-07-26 17:57:43.385700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be40a92bfaaf'
down_revision: Union[str, None] = '497ec58be36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_role_images', sa.Column('version', sa.Integer(), nullable=True, comment='图片版本'))
    op.add_column('clone_scene_images', sa.Column('version', sa.Integer(), nullable=True, comment='图片版本'))
    op.add_column('clone_segment_images', sa.Column('version', sa.Integer(), nullable=True, comment='图片版本'))
    
    op.execute("UPDATE clone_role_images SET version = 0")
    op.execute("UPDATE clone_scene_images SET version = 0")
    op.execute("UPDATE clone_segment_images SET version = 0")
    
    op.alter_column('clone_role_images', 'version', nullable=False)
    op.alter_column('clone_scene_images', 'version', nullable=False)
    op.alter_column('clone_segment_images', 'version', nullable=False)
    # ### end Alembic commands ###
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clone_segment_images', 'version')
    op.drop_column('clone_scene_images', 'version')
    op.drop_column('clone_role_images', 'version')
    # ### end Alembic commands ###
