"""add info to clone_videos

Revision ID: c443ac8b8734
Revises: 90ca846aba78
Create Date: 2026-08-01 22:07:46.362089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c443ac8b8734'
down_revision: Union[str, None] = '90ca846aba78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ENUM_NAME = 'clonestatus'

def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE IF NOT EXISTS 'FRAME'")
        op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE IF NOT EXISTS 'FRAME_DONE'")
        op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE IF NOT EXISTS 'SEGMENT_VIDEO'")
        op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE IF NOT EXISTS 'SEGMENT_VIDEO_DONE'")
        op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE IF NOT EXISTS 'MERGE_VIDEO'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_videos', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('clone_videos', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('clone_videos', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('clone_videos', sa.Column('rate', sa.Integer(), nullable=True))
    op.add_column('clone_videos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('clone_videos', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_videos', sa.Column('error_message', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('clone_videos', 'updated_at')
    op.drop_column('clone_videos', 'rate')
    op.drop_column('clone_videos', 'height')
    op.drop_column('clone_videos', 'width')
    op.drop_column('clone_videos', 'version')
    # ### end Alembic commands ###
