"""convert text to json

Revision ID: c9bd1aabb92a
Revises: 8631600b9bce
Create Date: 2026-06-04 15:44:14.224758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9bd1aabb92a'
down_revision: Union[str, None] = '8631600b9bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clone_scripts', 'clone_parse_pointer',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               postgresql_using='clone_parse_pointer::json',
               existing_comment='复刻解析重点信息',
               existing_nullable=True)
    op.drop_constraint('clone_scripts_script_id_key', 'clone_scripts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clone_scripts_script_id_key', 'clone_scripts', ['script_id'])
    op.alter_column('clone_scripts', 'clone_parse_pointer',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_comment='复刻解析重点信息',
               existing_nullable=True)
    # ### end Alembic commands ###
