"""add role view in segments table

Revision ID: cb69ce16e987
Revises: 1b7ce5112992
Create Date: 2026-07-22 19:25:44.335541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb69ce16e987'
down_revision: Union[str, None] = '1b7ce5112992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_script_segments', sa.Column('role_view_info', sa.JSON(), nullable=True, comment='分镜角色视觉描述'))
    op.add_column('clone_script_segments', sa.Column('scene_name', sa.String(length=256), nullable=True, comment='场景名'))
    op.add_column('clone_script_segments', sa.Column('shot_type', sa.String(length=128), nullable=True, comment='镜头描述'))
    op.alter_column('clone_script_segments', 'shot_description',
               existing_type=sa.TEXT(),
               comment='分镜描述提示词',
               existing_nullable=True)
    op.alter_column('clone_script_segments', 'dialogue',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='分镜对话',
               existing_nullable=True)
    op.alter_column('clone_script_segments', 'first_frame_path',
               existing_type=sa.VARCHAR(length=256),
               comment='分镜首帧路径',
               existing_nullable=True)
    op.alter_column('clone_script_segments', 'segment_type',
               existing_type=sa.VARCHAR(length=128),
               comment='分镜整体情绪',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clone_script_segments', 'segment_type',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='分镜整体情绪',
               existing_nullable=True)
    op.alter_column('clone_script_segments', 'first_frame_path',
               existing_type=sa.VARCHAR(length=256),
               comment=None,
               existing_comment='分镜首帧路径',
               existing_nullable=True)
    op.alter_column('clone_script_segments', 'dialogue',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='分镜对话',
               existing_nullable=True)
    op.alter_column('clone_script_segments', 'shot_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='分镜描述提示词',
               existing_nullable=True)
    op.drop_column('clone_script_segments', 'shot_type')
    op.drop_column('clone_script_segments', 'scene_name')
    op.drop_column('clone_script_segments', 'role_view_info')
    # ### end Alembic commands ###
