"""add is_novel to clone_scripts

Revision ID: e8cb23ac5dac
Revises: e5f6a7b8c9d0
Create Date: 2026-08-21 14:06:58.861620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8cb23ac5dac'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_script_segments', sa.Column('is_novel', sa.Boolean(), nullable=True, comment='该分镜是否属于小说生成'))
    op.alter_column('clone_scripts', 'source_type',
               existing_type=sa.VARCHAR(length=16),
               comment='工作台来源：CLONE=复刻剧本 / ORIGINAL=原片直转渲染 / NOVEL=小说转剧本',
               existing_nullable=False,
               existing_server_default=sa.text("'CLONE'::character varying"))
    op.alter_column('clone_scripts', 'clone_parse_pointer',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='解析重点信息（CloneAnalysisFocus JSON）',
               existing_comment='复刻剧本解析',
               existing_nullable=True)
    op.alter_column('scripts', 'parse_pointer',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='解析重点信息（CloneAnalysisFocus JSON）',
               existing_comment='解析重点信息',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scripts', 'parse_pointer',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='解析重点信息',
               existing_comment='解析重点信息（CloneAnalysisFocus JSON）',
               existing_nullable=True)
    op.alter_column('clone_scripts', 'clone_parse_pointer',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='复刻剧本解析',
               existing_comment='解析重点信息（CloneAnalysisFocus JSON）',
               existing_nullable=True)
    op.alter_column('clone_scripts', 'source_type',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='工作台来源：CLONE=复刻剧本 / ORIGINAL=原片直转渲染 / NOVEL=小说转剧本',
               existing_nullable=False,
               existing_server_default=sa.text("'CLONE'::character varying"))
    op.drop_column('clone_script_segments', 'is_novel')
    # ### end Alembic commands ###
