"""add name_comfy

Revision ID: ebbd4c00f32c
Revises: be40a92bfaaf
Create Date: 2026-07-28 20:34:45.117077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbd4c00f32c'
down_revision: Union[str, None] = 'be40a92bfaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clone_role_images', sa.Column('name_comfy', sa.String(length=128), nullable=True, comment='图片再comfy中名称，用于图生图、图生视频'))
    op.add_column('clone_scene_images', sa.Column('name_comfy', sa.String(length=128), nullable=True, comment='图片再comfy中名称，用于图生图、图生视频'))
    op.add_column('clone_segment_images', sa.Column('name_comfy', sa.String(length=128), nullable=True, comment='图片再comfy中名称，用于图生图、图生视频'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clone_segment_images', 'name_comfy')
    op.drop_column('clone_scene_images', 'name_comfy')
    op.drop_column('clone_role_images', 'name_comfy')
    # ### end Alembic commands ###
